files:
  - source: /src/generated/resources/assets/deeperdarker/lang/en_us.json
    translation: /src/main/resources/assets/deeperdarker/lang/%locale_with_underscore%.json
  - source: src/main/resources/data/deeperdarker/patchouli_books/wanderers_notebook/en_us
    translation: src/main/resources/data/deeperdarker/patchouli_books/wanderers_notebook/%locale_with_underscore%
