modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"
issueTrackerURL = "https://github.com/nitrodynamite18/DeeperAndDarker/issues"

[[mods]]
    modId = "deeperdarker"
    version = "0.0.1"
    displayName = "Deeper and Darker"
    credits = '''
    VanillaTweaks, for the recipes.
    My sister, for helping create the textures. Her YouTube channel: https://www.youtube.com/channel/UCgaSBWe-EfZ-SiyRsotHKBw
    '''
    authors = "nitro_dynamite18"
    description = '''This mod adds new features to the Minecraft 1.19 Deep Dark biome to make it feel more complete. It also has compatibility features for Quark and TeamAbnormals' Buzzier Bees mod.'''

[[dependencies.deeperdarker]]
    modId = "forge"
    mandatory = true
    versionRange = "[41, 42)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.deeperdarker]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19, 1.20)"
    ordering = "NONE"
    side = "BOTH"