name: Gradle Build

on:
  push:
    branches: [ "forge-1.20" ]
  pull_request:
    branches: [ "forge-1.20" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build
